---
-   name: Install dependencies
    become: yes
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
      update_cache: yes

-   name: Add GPG key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

-   name: Verify fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

-   name: Set up the repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
      filename: docker
      update_cache: yes

-   name: Install Docker
    become: yes
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    notify: Start docker on boot

-   name: Install Docker Compose
    become: yes
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      group: docker
      mode: 'u+x,g+x'

-   name: Set periodic Docker prune
    become: yes
    cron:
      name: docker-prune
      job: 'docker system prune -af --filter "until=$((30*24))h"'
      minute: '0'
      hour: '1'

-   name: Remove useless packages
    become: yes
    apt:
      autoclean: yes

-   name: Remove useless dependencies
    become: yes
    apt:
      autoremove: yes
